booking_api/urls.py
from django.urls import path
from .views import BookingListCreate, BookingSearch
app_name = 'booking_api'

urlpatterns = [
    path('booking_list_create', BookingListCreate.as_view(), name='booking_list_create'),
    path('booking_search/<int:pk>', BookingSearch.as_view(), name='booking_search'),
]

portal/urls.py
from django.urls import path
from .views import Portal, StaffInformation, StaffUpdate, StaffDelete, ProductDetail, ProductUpdate, ProductDelete, BookingRecord, BookingUpdate, BookingDelete, Logout

app_name = 'portal'

urlpatterns = [
    path('', Portal.as_view(), name='portal'),
    path('staff_information', StaffInformation.as_view(), name='staff_information'),
    path('staff_update', StaffUpdate.as_view(), name='staff_update'),
    path('staff_delete', StaffDelete.as_view(), name='staff_delete'),
    path('product_detail', ProductDetail.as_view(), name='product_detail'),
    path('product_update', ProductUpdate.as_view(), name='product_update'),
    path('product_delete', ProductDelete.as_view(), name='product_delete'),
    path('booking_record', BookingRecord.as_view(), name='booking_record'),
    path('booking_update', BookingUpdate.as_view(), name='booking_update'),
    path('booking_delete', BookingDelete.as_view(), name='booking_delete'),
    path('logout', Logout.as_view(), name='logout'),
]

product_api/urls.py
from django.urls import path
from .views import ProductListCreate, ProductSearch

app_name = 'product_api'

urlpatterns = [
    path('product_list_create', ProductListCreate.as_view(), name='product_list_create'),
    path('product_search/<int:pk>', ProductSearch.as_view(), name='product_search'),
]

staff_api/urls.py
from django.urls import path
from .views import StaffListCreate, StaffSearch

app_name = 'staff_api'

urlpatterns = [
    path('staff_list_create', StaffListCreate.as_view(), name='staff_list_create'),
    path('staff_search/<int:pk>', StaffSearch.as_view(), name='staff_search'),
]

staff_portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login_registration.urls')),
    path('portal/', include('portal.urls')),
    path('booking/', include('booking_api.urls')),
    path('product/', include('product_api.urls')),
    path('staff/', include('staff_api.urls')),
]

portal/models.py
from django.db import models

# Create your models here.

portal/views.py
from django.views import View
from django.shortcuts import redirect, render
from staff_api.models import Staff
from product_api.models import Product
from booking_api.models import Booking

class Portal(View):

    def get(self, request):

        if request.session.get('login'):

            return render(request, 'portal.html')
        else:

            return redirect('login_registration:main')

class StaffInformation(View):

    def get(self, request):

        if request.session.get('login'):

            return render(request, 'staff_information.html')
        else:

            return redirect('login_registration:main')

class StaffUpdate(View):

    def get(self, request):

        if request.session.get('login'):

            return render(request, 'staff_update.html')
        else:

            return redirect('login_registration:main')

    def post(self, request):

        id = request.POST.get('id')
        name = request.POST.get('name')
        age = request.POST.get('age')
        gender = request.POST.get('gender')
        position = request.POST.get('position')
        department = request.POST.get('department')
        salary = request.POST.get('salary')

        try:

            update_staff = Staff.objects.get(pk=id)
        except Staff.DoesNotExist:

            return redirect('staff_api:staff_search', pk=id)
        
        update_staff.name = name
        update_staff.age = age
        update_staff.gender = gender
        update_staff.position = position
        update_staff.department = department
        update_staff.salary = salary
        update_staff.save()

        return redirect('staff_api:staff_list_create')

class StaffDelete(View):

    def get(self, request):

        if request.session.get('login'):

            return render(request, 'staff_delete.html')
        else:

            return redirect('login_registration:main')

    def post(self, request):

        id = request.POST.get('id')

        try:

            staff = Staff.objects.get(pk=id)
        except Staff.DoesNotExist:

            return redirect('staff_api:staff_search', pk=id)
        
        staff.delete()

        return redirect('staff_api:staff_list_create')

class ProductUpdate(View):

    def get(self, request):

        if request.session.get('login'):

            return render(request, 'product_update.html')
        else:

            return redirect('login_registration:main')

    def post(self, request):

        id = request.POST.get('id')
        product = request.POST.get('product')
        category = request.POST.get('category')
        inventory = request.POST.get('inventory')
        price = request.POST.get('price')

        try:

            update_product = Product.objects.get(pk=id)
        except Product.DoesNotExist:

            return redirect('product_api:product_search', pk=id)
        
        update_product.product = product
        update_product.category = category
        update_product.inventory = inventory
        update_product.price = price
        update_product.save()

        return redirect('product_api:product_list_create')

class ProductDelete(View):

    def get(self, request):

        if request.session.get('login'):

            return render(request, 'product_delete.html')
        else:

            return redirect('login_registration:main')

    def post(self, request):

        id = request.POST.get('id')

        try:

            product = Product.objects.get(pk=id)
        except Product.DoesNotExist:

            return redirect('product_api:product_search', pk=id)
        
        product.delete()

        return redirect('product_api:product_list_create')
    
class ProductDetail(View):

    def get(self, request):

        if request.session.get('login'):

            return render(request, 'product_detail.html')
        else:

            return redirect('login_registration:main')
    
class BookingRecord(View):

    def get(self, request):

        if request.session.get('login'):

            return render(request, 'booking_record.html')
        else:

            return redirect('login_registration:main')

class BookingUpdate(View):

    def get(self, request):

        if request.session.get('login'):

            return render(request, 'booking_update.html')
        else:

            return redirect('login_registration:main')

    def post(self, request):

        id = request.POST.get('id')
        customer = request.POST.get('customer')
        age = request.POST.get('age')
        gender = request.POST.get('gender')
        email = request.POST.get('email')
        phone_number = request.POST.get('phone_number')
        address = request.POST.get('address')
        booking_date = request.POST.get('booking_date')
        booking_time = request.POST.get('booking_time')
        booking_status = request.POST.get('booking_status')
        payment_status = request.POST.get('payment_status')
        payment_method = request.POST.get('payment_method')
        payment_date = request.POST.get('payment_date')
        payment_amount = request.POST.get('payment_amount')
        service = request.POST.get('service')

        try:

            update_booking = Booking.objects.get(pk=id)
        except Booking.DoesNotExist:

            return redirect('booking_api:booking_search', pk=id)
        
        update_booking.customer = customer
        update_booking.age = age
        update_booking.gender = gender
        update_booking.email = email
        update_booking.phone_number = phone_number
        update_booking.address = address
        update_booking.booking_date = booking_date
        update_booking.booking_time = booking_time
        update_booking.booking_status = booking_status
        update_booking.payment_status = payment_status
        update_booking.payment_method = payment_method
        update_booking.payment_date = payment_date
        update_booking.payment_amount = payment_amount
        update_booking.service = service
        update_booking.save()

        return redirect('booking_api:booking_list_create')

class BookingDelete(View):

    def get(self, request):

        if request.session.get('login'):

            return render(request, 'booking_delete.html')
        else:

            return redirect('login_registration:main')

    def post(self, request):

        id = request.POST.get('id')

        try:

            booking = Booking.objects.get(pk=id)
        except Booking.DoesNotExist:

            return redirect('booking_api:booking_search', pk=id)
        
        booking.delete()

        return redirect('booking_api:booking_list_create')
    
class Logout(View):

    def get(self, request):

        request.session.flush()
        
        return redirect('login_registration:main')

portal/templates/booking_delete.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Delete Booking Record</title>
</head>

<body>
    <div class="container" style="display: flex; justify-content: center; align-items: center; height: 100vh;">
        <form action="{% url 'portal:booking_delete' %}" method="POST">
            {% csrf_token %}
            <h2>Delete</h2>
            <div class="mb-3">
                <label for="id" class="form-label">ID</label>
                <select class="form-select" aria-label="id" name="id" id="id" required>
                    <option value="1" selected>1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    <option value="6">6</option>
                    <option value="7">7</option>
                    <option value="8">8</option>
                    <option value="9">9</option>
                    <option value="10">10</option>
                    <option value="11">11</option>
                    <option value="12">12</option>
                    <option value="13">13</option>
                    <option value="14">14</option>
                    <option value="15">15</option>
                    <option value="16">16</option>
                    <option value="17">17</option>
                    <option value="18">18</option>
                    <option value="19">19</option>
                    <option value="20">20</option>
                    <option value="21">21</option>
                    <option value="22">22</option>
                    <option value="23">23</option>
                    <option value="24">24</option>
                    <option value="25">25</option>
                    <option value="26">26</option>
                    <option value="27">27</option>
                    <option value="28">28</option>
                    <option value="29">29</option>
                    <option value="30">30</option>
                </select>
            </div>

            <button type="submit" class="btn btn-danger">Delete</button>
            <a href="{% url 'portal:booking_record' %}" type="button" class="btn btn-dark">Back</a>
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

portal/templates/booking_record.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Booking Record</title>
</head>

<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'portal:portal' %}">Staff Portal</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'portal:portal' %}">Back</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                            href="{% url 'booking_api:booking_list_create' %}">Booking List & Create</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'portal:booking_update' %}">Booking
                            Update</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                            href="{% url 'portal:booking_delete' %}">Booking Delete</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'portal:logout' %}">Logout</a>
                    </li>
                </ul>
                <div class="d-flex" role="search" method="GET">
                    <input class="form-control me-2" type="search" placeholder="Search Booking by ID"
                        aria-label="Search" id="id" oninput="this.value = this.value.replace(/^0(?!$)|[^0-9]/g, '');">
                    <a href="#" class="btn btn-outline-light" id="search" type="submit">Search</a>
                </div>
            </div>
        </div>
    </nav>

    <div style="display: flex; justify-content: center; align-items: center; height: 100vh;">
        <div class="card" style="width: 19rem; height: 200px; margin: 20px;">
            <div class="card-body">
                <h2 class="card-title mb-5">List & Create</h2>
                <a href="{% url 'booking_api:booking_list_create' %}" class="btn btn-dark">See</a>
            </div>
        </div>
        <div class="card" style="width: 19rem; height: 200px; margin: 20px;">
            <div class="card-body">
                <h2 class="card-title mb-5">Booking Update</h2>
                <a href="{% url 'portal:booking_update' %}" class="btn btn-dark">Update</a>
            </div>
        </div>
        <div class="card" style="width: 19rem; height: 200px; margin: 20px;">
            <div class="card-body">
                <h2 class="card-title mb-5">Booking Delete</h2>
                <a href="{% url 'portal:booking_delete' %}" class="btn btn-dark">Delete</a>
            </div>
        </div>
    </div>

    <script>
        document.getElementById('search').addEventListener('click', function (event) {
            event.preventDefault();
            var staffId = document.getElementById('id').value;
            var url = `{% url 'booking_api:booking_search' 0 %}`.replace('0', staffId);
            window.location.href = url;
        });
    </script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

portal/templates/portal.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Staff Portal</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'portal:portal' %}">Staff Portal</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'portal:staff_information' %}">Staff
                            Information</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'portal:product_detail' %}">Product
                            Detail</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'portal:booking_record' %}">Booking
                            Record</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'portal:logout' %}">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div style="display: flex; justify-content: center; align-items: center; height: 100vh;">
        <div class="card" style="width: 18rem; margin: 20px;">
            <div class="card-body">
                <h2 class="card-title mb-5">Staff Information</h2>
                <a href="{% url 'portal:staff_information' %}" class="btn btn-dark">See</a>
            </div>
        </div>
        <div class="card" style="width: 18rem; margin: 20px;">
            <div class="card-body">
                <h2 class="card-title mb-5">Product Detail</h2>
                <a href="{% url 'portal:product_detail' %}" class="btn btn-dark">Detail</a>
            </div>
        </div>
        <div class="card" style="width: 18rem; margin: 20px;">
            <div class="card-body">
                <h2 class="card-title mb-5">Booking Record</h2>
                <a href="{% url 'portal:booking_record' %}" class="btn btn-dark">Check</a>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

portal/templates/product_delete.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Delete Product Information</title>
</head>

<body>
    <div class="container" style="display: flex; justify-content: center; align-items: center; height: 100vh;">
        <form action="{% url 'portal:product_delete' %}" method="POST">
            {% csrf_token %}
            <h2>Delete</h2>
            <div class="mb-3">
                <label for="id" class="form-label">ID</label>
                <select class="form-select" aria-label="id" name="id" id="id" required>
                    <option value="1" selected>1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    <option value="6">6</option>
                    <option value="7">7</option>
                    <option value="8">8</option>
                    <option value="9">9</option>
                    <option value="10">10</option>
                    <option value="11">11</option>
                    <option value="12">12</option>
                    <option value="13">13</option>
                    <option value="14">14</option>
                    <option value="15">15</option>
                    <option value="16">16</option>
                    <option value="17">17</option>
                    <option value="18">18</option>
                    <option value="19">19</option>
                    <option value="20">20</option>
                    <option value="21">21</option>
                    <option value="22">22</option>
                    <option value="23">23</option>
                    <option value="24">24</option>
                    <option value="25">25</option>
                    <option value="26">26</option>
                    <option value="27">27</option>
                    <option value="28">28</option>
                    <option value="29">29</option>
                    <option value="30">30</option>
                </select>
            </div>

            <button type="submit" class="btn btn-danger">Delete</button>
            <a href="{% url 'portal:product_detail' %}" type="button" class="btn btn-dark">Back</a>
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

portal/templates/product_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Product Detail</title>
</head>

<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'portal:portal' %}">Staff Portal</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'portal:portal' %}">Back</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                            href="{% url 'product_api:product_list_create' %}">Product List & Create</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'portal:product_update' %}">Product
                            Update</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                            href="{% url 'portal:product_delete' %}">Product Delete</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'portal:logout' %}">Logout</a>
                    </li>
                </ul>
                <div class="d-flex" role="search" method="GET">
                    <input class="form-control me-2" type="search" placeholder="Search Product by ID"
                        aria-label="Search" id="id" oninput="this.value = this.value.replace(/^0(?!$)|[^0-9]/g, '');">
                    <a href="#" class="btn btn-outline-light" id="search" type="submit">Search</a>
                </div>
            </div>
        </div>
    </nav>

    <div style="display: flex; justify-content: center; align-items: center; height: 100vh;">
        <div class="card" style="width: 19rem; height: 200px; margin: 20px;">
            <div class="card-body">
                <h2 class="card-title mb-5">List & Create</h2>
                <a href="{% url 'product_api:product_list_create' %}" class="btn btn-dark">See</a>
            </div>
        </div>
        <div class="card" style="width: 19rem; height: 200px; margin: 20px;">
            <div class="card-body">
                <h2 class="card-title mb-5">Product Update</h2>
                <a href="{% url 'portal:product_update' %}" class="btn btn-dark">Update</a>
            </div>
        </div>
        <div class="card" style="width: 19rem; height: 200px; margin: 20px;">
            <div class="card-body">
                <h2 class="card-title mb-5">Product Delete</h2>
                <a href="{% url 'portal:product_delete' %}" class="btn btn-dark">Delete</a>
            </div>
        </div>
    </div>

    <script>
        document.getElementById('search').addEventListener('click', function (event) {
            event.preventDefault();
            var staffId = document.getElementById('id').value;
            var url = `{% url 'product_api:product_search' 0 %}`.replace('0', staffId);
            window.location.href = url;
        });
    </script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

portal/templates/staff_information.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Staff Information</title>
</head>

<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'portal:portal' %}">Staff Portal</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'portal:portal' %}">Back</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                            href="{% url 'staff_api:staff_list_create' %}">Staff
                            List & Create</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'portal:staff_update' %}">Staff
                            Update</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'portal:staff_delete' %}">Staff
                            Delete</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'portal:logout' %}">Logout</a>
                    </li>
                </ul>
                <div class="d-flex" role="search" method="GET">
                    <input class="form-control me-2" type="search" placeholder="Search Staff by ID" aria-label="Search"
                        id="id" oninput="this.value = this.value.replace(/^0(?!$)|[^0-9]/g, '');">
                    <a href="#" class="btn btn-outline-light" id="search" type="submit">Search</a>
                </div>
            </div>
        </div>
    </nav>

    <div style="display: flex; justify-content: center; align-items: center; height: 100vh;">
        <div class="card" style="width: 19rem; height: 200px; margin: 20px;">
            <div class="card-body">
                <h2 class="card-title mb-5">List & Create</h2>
                <a href="{% url 'staff_api:staff_list_create' %}" class="btn btn-dark">See</a>
            </div>
        </div>
        <div class="card" style="width: 19rem; height: 200px; margin: 20px;">
            <div class="card-body">
                <h2 class="card-title mb-5">Staff Update</h2>
                <a href="{% url 'portal:staff_update' %}" class="btn btn-dark">Update</a>
            </div>
        </div>
        <div class="card" style="width: 19rem; height: 200px; margin: 20px;">
            <div class="card-body">
                <h2 class="card-title mb-5">Staff Delete</h2>
                <a href="{% url 'portal:staff_delete' %}" class="btn btn-dark">Delete</a>
            </div>
        </div>
    </div>

    <script>
        document.getElementById('search').addEventListener('click', function (event) {
            event.preventDefault();
            var staffId = document.getElementById('id').value;
            var url = `{% url 'staff_api:staff_search' 0 %}`.replace('0', staffId);
            window.location.href = url;
        });
    </script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>