login_registration/urls.py
from django.urls import path
from .views import Main, Login, Registration

app_name = 'login_registration'

urlpatterns = [
    path('', Main.as_view(), name='main'),
    path('login_page', Login.as_view(), name='login_page'),
    path('registration_page', Registration.as_view(), name='registration_page'),
]

portal/urls.py
from django.urls import path
from .views import Portal, StaffInformation, StaffUpdate, StaffDelete, ProductDetail, ProductUpdate, ProductDelete, BookingRecord, BookingUpdate, BookingDelete, Logout

app_name = 'portal'

urlpatterns = [
    path('', Portal.as_view(), name='portal'),
    path('staff_information', StaffInformation.as_view(), name='staff_information'),
    path('staff_update', StaffUpdate.as_view(), name='staff_update'),
    path('staff_delete', StaffDelete.as_view(), name='staff_delete'),
    path('product_detail', ProductDetail.as_view(), name='product_detail'),
    path('product_update', ProductUpdate.as_view(), name='product_update'),
    path('product_delete', ProductDelete.as_view(), name='product_delete'),
    path('booking_record', BookingRecord.as_view(), name='booking_record'),
    path('booking_update', BookingUpdate.as_view(), name='booking_update'),
    path('booking_delete', BookingDelete.as_view(), name='booking_delete'),
    path('logout', Logout.as_view(), name='logout'),
]

staff_portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login_registration.urls')),
    path('portal/', include('portal.urls')),
    path('booking/', include('booking_api.urls')),
    path('product/', include('product_api.urls')),
    path('staff/', include('staff_api.urls')),
]

login_registration/models.py
from django.db import models

class LoginRegistration(models.Model):
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    salt = models.BinaryField()

login_registration/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from django.views import View
from .models import LoginRegistration
import os, hashlib

class Main(View):

    def get(self, request):

        if request.session.get('login'):
            
            return redirect('portal:portal')
        else:

            return render(request, 'main.html')
        
class Login(View):

    def get(self, request):

        if request.session.get('login'):
            
            return redirect('portal:portal')
        else:

            return render(request, 'login_page.html')
        
            
    def post(self, request):

        username = request.POST.get('username')
        password = request.POST.get('password')

        try:

            login = LoginRegistration.objects.get(username = username)

        except LoginRegistration.DoesNotExist:

            login_fail_message = 'Username or password incorrect.'
            alert_style = 'alert alert-danger'
     
            messages.error(request, login_fail_message, extra_tags=alert_style)

            return redirect('login_registration:login_page')
        
        stored_salt = login.salt
        stored_hashed_password = login.password

        password_bytes = password.encode('utf-8')
        hashed_input_password = hashlib.sha256(password_bytes + stored_salt).hexdigest()
        print(hashed_input_password)

        if hashed_input_password == stored_hashed_password:

            request.session['login'] = True

            return redirect('portal:portal')
        
        else:

            return redirect('login_registration:login_page')
    
class Registration(View):

    def get(self, request):

        return render(request, 'registration_page.html')
    
    def post(self, request):

        username = request.POST.get('username')
        password = request.POST.get('password')


        if LoginRegistration.objects.filter(username = username).exists():

            username_used_message = 'Username had been used.'
            messages.error(request, username_used_message)

            return redirect('login_registration:registration_page')
        else:
            
            salt = os.urandom(16)
            password_bytes = password.encode('utf-8')
            hashed_password = hashlib.sha256(password_bytes + salt).hexdigest()

            registration = LoginRegistration(username = username, password = hashed_password, salt = salt)
            registration.save()
            print(hashed_password)

            registration_success_message = 'Registration is succcessful.'
            success_style = 'alert alert-success'

            messages.success(request, registration_success_message, extra_tags=success_style)
        
            return redirect('login_registration:login_page')

login_registration/templates/login_page.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Login</title>
</head>

<body>
    <div class="container" style="display: flex; justify-content: center; align-items: center; height: 100vh;">
        <form action="{% url 'login_registration:login_page' %}" method="POST">
            {% csrf_token %}
            <h2>Login</h2>
            {% if messages %}
            {% for message in messages %}
            <div class='{{ message.tags }}' role="alert">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            <div class="mb-3">
                <label for="username" class="form-label">Username</label>
                <input type="text" class="form-control" name="username" id="username" aria-describedby="username"
                    required>
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">Password</label>
                <input type="password" class="form-control" name="password" id="password" required>
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
            <a href="{% url 'login_registration:main' %}" type="button" class="btn btn-dark">Back</a>
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

login_registration/templates/main.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Staff Portal System</title>
</head>

<body>

    <div style="display: flex; justify-content: center; align-items: center; height: 100vh;">
        <div class="card" style="width: 18rem; margin: 20px;">
            <div class="card-body">
                <h2 class="card-title mb-5">Staff Portal</h2>
                <a href="{% url 'login_registration:login_page' %}" class="btn btn-dark">Login</a>
            </div>
        </div>
        <div class="card" style="width: 18rem; margin: 20px;">
            <div class="card-body">
                <h2 class="card-title mb-5">New Staff</h2>
                <a href="{% url 'login_registration:registration_page' %}" class="btn btn-dark">Registration</a>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

login_registration/templates/registration_page.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Registration</title>
</head>

<body>
    <div class="container" style="display: flex; justify-content: center; align-items: center; height: 100vh;">
        <form action="{% url 'login_registration:registration_page' %}" method="POST">
            {% csrf_token %}
            <h2>Registration</h2>
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            <div class="mb-3">
                <label for="username" class="form-label">Username</label>
                <input type="text" class="form-control" name="username" id="username" aria-describedby="username"
                    required>
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">Password</label>
                <input type="password" class="form-control" name="password" id="password" required>
            </div>
            <button type="submit" class="btn btn-primary">Register</button>
            <a href="{% url 'login_registration:main' %}" type="button" class="btn btn-dark">Back</a>
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>